export interface CountryData {
  name: string;
  code: string;  // Dial code e.g. "+61"
  short: string; // ISO 3166-1 alpha-3 code e.g. "AUS"
  flag: string;  // Emoji flag e.g. "🇦🇺"
  iso2: string;  // ISO 2-letter e.g. "AU"
}

export const countryList: CountryData[] = [
  { name: "Australia", code: "+61", short: "AUS", flag: "🇦🇺", iso2: "AU" },
  { name: "New Zealand", code: "+64", short: "NZL", flag: "🇳🇿", iso2: "NZ" },
  { name: "India", code: "+91", short: "IND", flag: "🇮🇳", iso2: "IN" },
  { name: "United Kingdom", code: "+44", short: "GBR", flag: "🇬🇧", iso2: "GB" },
  { name: "United States", code: "+1", short: "USA", flag: "🇺🇸", iso2: "US" },
  { name: "Canada", code: "+1", short: "CAN", flag: "🇨🇦", iso2: "CA" },
  { name: "Singapore", code: "+65", short: "SGP", flag: "🇸🇬", iso2: "SG" },
  { name: "United Arab Emirates", code: "+971", short: "ARE", flag: "🇦🇪", iso2: "AE" },
  { name: "Afghanistan", code: "+93", short: "AFG", flag: "🇦🇫", iso2: "AF" },
  { name: "Albania", code: "+355", short: "ALB", flag: "🇦🇱", iso2: "AL" },
  { name: "Algeria", code: "+213", short: "DZA", flag: "🇩🇿", iso2: "DZ" },
  { name: "American Samoa", code: "+1-684", short: "ASM", flag: "🇦🇸", iso2: "AS" },
  { name: "Andorra", code: "+376", short: "AND", flag: "🇦🇩", iso2: "AD" },
  { name: "Angola", code: "+244", short: "AGO", flag: "🇦🇴", iso2: "AO" },
  { name: "Anguilla", code: "+1-264", short: "AIA", flag: "🇦🇮", iso2: "AI" },
  { name: "Antigua and Barbuda", code: "+1-268", short: "ATG", flag: "🇦🇬", iso2: "AG" },
  { name: "Argentina", code: "+54", short: "ARG", flag: "🇦🇷", iso2: "AR" },
  { name: "Armenia", code: "+374", short: "ARM", flag: "🇦🇲", iso2: "AM" },
  { name: "Aruba", code: "+297", short: "ABW", flag: "🇦🇼", iso2: "AW" },
  { name: "Austria", code: "+43", short: "AUT", flag: "🇦🇹", iso2: "AT" },
  { name: "Azerbaijan", code: "+994", short: "AZE", flag: "🇦🇿", iso2: "AZ" },
  { name: "Bahamas", code: "+1-242", short: "BHS", flag: "🇧🇸", iso2: "BS" },
  { name: "Bahrain", code: "+973", short: "BHR", flag: "🇧🇭", iso2: "BH" },
  { name: "Bangladesh", code: "+880", short: "BGD", flag: "🇧🇩", iso2: "BD" },
  { name: "Barbados", code: "+1-246", short: "BRB", flag: "🇧🇧", iso2: "BB" },
  { name: "Belarus", code: "+375", short: "BLR", flag: "🇧🇾", iso2: "BY" },
  { name: "Belgium", code: "+32", short: "BEL", flag: "🇧🇪", iso2: "BE" },
  { name: "Belize", code: "+501", short: "BLZ", flag: "🇧🇿", iso2: "BZ" },
  { name: "Benin", code: "+229", short: "BEN", flag: "🇧🇯", iso2: "BJ" },
  { name: "Bermuda", code: "+1-441", short: "BMU", flag: "🇧🇲", iso2: "BM" },
  { name: "Bhutan", code: "+975", short: "BTN", flag: "🇧🇹", iso2: "BT" },
  { name: "Bolivia", code: "+591", short: "BOL", flag: "🇧🇴", iso2: "BO" },
  { name: "Bosnia and Herzegovina", code: "+387", short: "BIH", flag: "🇧🇦", iso2: "BA" },
  { name: "Botswana", code: "+267", short: "BWA", flag: "🇧🇼", iso2: "BW" },
  { name: "Brazil", code: "+55", short: "BRA", flag: "🇧🇷", iso2: "BR" },
  { name: "Brunei", code: "+673", short: "BRN", flag: "🇧🇳", iso2: "BN" },
  { name: "Bulgaria", code: "+359", short: "BGR", flag: "🇧🇬", iso2: "BG" },
  { name: "Burkina Faso", code: "+226", short: "BFA", flag: "🇧🇫", iso2: "BF" },
  { name: "Burundi", code: "+257", short: "BDI", flag: "🇧🇮", iso2: "BI" },
  { name: "Cambodia", code: "+855", short: "KHM", flag: "🇰🇭", iso2: "KH" },
  { name: "Cameroon", code: "+237", short: "CMR", flag: "🇨🇲", iso2: "CM" },
  { name: "Cape Verde", code: "+238", short: "CPV", flag: "🇨🇻", iso2: "CV" },
  { name: "Cayman Islands", code: "+1-345", short: "CYM", flag: "🇰🇾", iso2: "KY" },
  { name: "Central African Republic", code: "+236", short: "CAF", flag: "🇨🇫", iso2: "CF" },
  { name: "Chad", code: "+235", short: "TCD", flag: "🇹🇩", iso2: "TD" },
  { name: "Chile", code: "+56", short: "CHL", flag: "🇨🇱", iso2: "CL" },
  { name: "China", code: "+86", short: "CHN", flag: "🇨🇳", iso2: "CN" },
  { name: "Colombia", code: "+57", short: "COL", flag: "🇨🇴", iso2: "CO" },
  { name: "Comoros", code: "+269", short: "COM", flag: "🇰🇲", iso2: "KM" },
  { name: "Congo", code: "+242", short: "COG", flag: "🇨🇬", iso2: "CG" },
  { name: "Costa Rica", code: "+506", short: "CRI", flag: "🇨🇷", iso2: "CR" },
  { name: "Croatia", code: "+385", short: "HRV", flag: "🇭🇷", iso2: "HR" },
  { name: "Cuba", code: "+53", short: "CUB", flag: "🇨🇺", iso2: "CU" },
  { name: "Cyprus", code: "+357", short: "CYP", flag: "🇨🇾", iso2: "CY" },
  { name: "Czech Republic", code: "+420", short: "CZE", flag: "🇨🇿", iso2: "CZ" },
  { name: "Denmark", code: "+45", short: "DNK", flag: "🇩🇰", iso2: "DK" },
  { name: "Djibouti", code: "+253", short: "DJI", flag: "🇩🇯", iso2: "DJ" },
  { name: "Dominica", code: "+1-767", short: "DMA", flag: "🇩🇲", iso2: "DM" },
  { name: "Dominican Republic", code: "+1-809", short: "DOM", flag: "🇩🇴", iso2: "DO" },
  { name: "Ecuador", code: "+593", short: "ECU", flag: "🇪🇨", iso2: "EC" },
  { name: "Egypt", code: "+20", short: "EGY", flag: "🇪🇬", iso2: "EG" },
  { name: "El Salvador", code: "+503", short: "SLV", flag: "🇸🇻", iso2: "SV" },
  { name: "Equatorial Guinea", code: "+240", short: "GNQ", flag: "🇬🇶", iso2: "GQ" },
  { name: "Eritrea", code: "+291", short: "ERI", flag: "🇪🇷", iso2: "ER" },
  { name: "Estonia", code: "+372", short: "EST", flag: "🇪🇪", iso2: "EE" },
  { name: "Ethiopia", code: "+251", short: "ETH", flag: "🇪🇹", iso2: "ET" },
  { name: "Fiji", code: "+679", short: "FJI", flag: "🇫🇯", iso2: "FJ" },
  { name: "Finland", code: "+358", short: "FIN", flag: "🇫🇮", iso2: "FI" },
  { name: "France", code: "+33", short: "FRA", flag: "🇫🇷", iso2: "FR" },
  { name: "French Guiana", code: "+594", short: "GUF", flag: "🇬🇫", iso2: "GF" },
  { name: "French Polynesia", code: "+689", short: "PYF", flag: "🇵🇫", iso2: "PF" },
  { name: "Gabon", code: "+241", short: "GAB", flag: "🇬🇦", iso2: "GA" },
  { name: "Gambia", code: "+220", short: "GMB", flag: "🇬🇲", iso2: "GM" },
  { name: "Georgia", code: "+995", short: "GEO", flag: "🇬🇪", iso2: "GE" },
  { name: "Germany", code: "+49", short: "DEU", flag: "🇩🇪", iso2: "DE" },
  { name: "Ghana", code: "+233", short: "GHA", flag: "🇬🇭", iso2: "GH" },
  { name: "Gibraltar", code: "+350", short: "GIB", flag: "🇬🇮", iso2: "GI" },
  { name: "Greece", code: "+30", short: "GRC", flag: "🇬🇷", iso2: "GR" },
  { name: "Greenland", code: "+299", short: "GRL", flag: "🇬🇱", iso2: "GL" },
  { name: "Grenada", code: "+1-473", short: "GRD", flag: "🇬🇩", iso2: "GD" },
  { name: "Guadeloupe", code: "+590", short: "GLP", flag: "🇬🇵", iso2: "GP" },
  { name: "Guam", code: "+1-671", short: "GUM", flag: "🇬🇺", iso2: "GU" },
  { name: "Guatemala", code: "+502", short: "GTM", flag: "🇬🇹", iso2: "GT" },
  { name: "Guinea", code: "+224", short: "GIN", flag: "🇬🇳", iso2: "GN" },
  { name: "Guinea-Bissau", code: "+245", short: "GNB", flag: "🇬🇼", iso2: "GW" },
  { name: "Guyana", code: "+592", short: "GUY", flag: "🇬🇾", iso2: "GY" },
  { name: "Haiti", code: "+509", short: "HTI", flag: "🇭🇹", iso2: "HT" },
  { name: "Honduras", code: "+504", short: "HND", flag: "🇭🇳", iso2: "HN" },
  { name: "Hong Kong", code: "+852", short: "HKG", flag: "🇭🇰", iso2: "HK" },
  { name: "Hungary", code: "+36", short: "HUN", flag: "🇭🇺", iso2: "HU" },
  { name: "Iceland", code: "+354", short: "ISL", flag: "🇮🇸", iso2: "IS" },
  { name: "Indonesia", code: "+62", short: "IDN", flag: "🇮🇩", iso2: "ID" },
  { name: "Iran", code: "+98", short: "IRN", flag: "🇮🇷", iso2: "IR" },
  { name: "Iraq", code: "+964", short: "IRQ", flag: "🇮🇶", iso2: "IQ" },
  { name: "Ireland", code: "+353", short: "IRL", flag: "🇮🇪", iso2: "IE" },
  { name: "Israel", code: "+972", short: "ISR", flag: "🇮🇱", iso2: "IL" },
  { name: "Italy", code: "+39", short: "ITA", flag: "🇮🇹", iso2: "IT" },
  { name: "Ivory Coast", code: "+225", short: "CIV", flag: "🇨🇮", iso2: "CI" },
  { name: "Jamaica", code: "+1-876", short: "JAM", flag: "🇯🇲", iso2: "JM" },
  { name: "Japan", code: "+81", short: "JPN", flag: "🇯🇵", iso2: "JP" },
  { name: "Jordan", code: "+962", short: "JOR", flag: "🇯🇴", iso2: "JO" },
  { name: "Kazakhstan", code: "+7", short: "KAZ", flag: "🇰🇿", iso2: "KZ" },
  { name: "Kenya", code: "+254", short: "KEN", flag: "🇰🇪", iso2: "KE" },
  { name: "Kiribati", code: "+686", short: "KIR", flag: "🇰🇮", iso2: "KI" },
  { name: "Kuwait", code: "+965", short: "KWT", flag: "🇰🇼", iso2: "KW" },
  { name: "Kyrgyzstan", code: "+996", short: "KGZ", flag: "🇰🇬", iso2: "KG" },
  { name: "Laos", code: "+856", short: "LAO", flag: "🇱🇦", iso2: "LA" },
  { name: "Latvia", code: "+371", short: "LVA", flag: "🇱🇻", iso2: "LV" },
  { name: "Lebanon", code: "+961", short: "LBN", flag: "🇱🇧", iso2: "LB" },
  { name: "Lesotho", code: "+266", short: "LSO", flag: "🇱🇸", iso2: "LS" },
  { name: "Liberia", code: "+231", short: "LBR", flag: "🇱🇷", iso2: "LR" },
  { name: "Libya", code: "+218", short: "LBY", flag: "🇱🇾", iso2: "LY" },
  { name: "Liechtenstein", code: "+423", short: "LIE", flag: "🇱🇮", iso2: "LI" },
  { name: "Lithuania", code: "+370", short: "LTU", flag: "🇱🇹", iso2: "LT" },
  { name: "Luxembourg", code: "+352", short: "LUX", flag: "🇱🇺", iso2: "LU" },
  { name: "Macau", code: "+853", short: "MAC", flag: "🇲🇴", iso2: "MO" },
  { name: "Macedonia", code: "+389", short: "MKD", flag: "🇲🇰", iso2: "MK" },
  { name: "Madagascar", code: "+261", short: "MDG", flag: "🇲🇬", iso2: "MG" },
  { name: "Malawi", code: "+265", short: "MWI", flag: "🇲🇼", iso2: "MW" },
  { name: "Malaysia", code: "+60", short: "MYS", flag: "🇲🇾", iso2: "MY" },
  { name: "Maldives", code: "+960", short: "MDV", flag: "🇲🇻", iso2: "MV" },
  { name: "Mali", code: "+223", short: "MLI", flag: "🇲🇱", iso2: "ML" },
  { name: "Malta", code: "+356", short: "MLT", flag: "🇲🇹", iso2: "MT" },
  { name: "Marshall Islands", code: "+692", short: "MHL", flag: "🇲🇭", iso2: "MH" },
  { name: "Martinique", code: "+596", short: "MTQ", flag: "🇲🇶", iso2: "MQ" },
  { name: "Mauritania", code: "+222", short: "MRT", flag: "🇲🇷", iso2: "MR" },
  { name: "Mauritius", code: "+230", short: "MUS", flag: "🇲🇺", iso2: "MU" },
  { name: "Mexico", code: "+52", short: "MEX", flag: "🇲🇽", iso2: "MX" },
  { name: "Micronesia", code: "+691", short: "FSM", flag: "🇫🇲", iso2: "FM" },
  { name: "Moldova", code: "+373", short: "MDA", flag: "🇲🇩", iso2: "MD" },
  { name: "Monaco", code: "+377", short: "MCO", flag: "🇲🇨", iso2: "MC" },
  { name: "Mongolia", code: "+976", short: "MNG", flag: "🇲🇳", iso2: "MN" },
  { name: "Montenegro", code: "+382", short: "MNE", flag: "🇲🇪", iso2: "ME" },
  { name: "Montserrat", code: "+1-664", short: "MSR", flag: "🇲🇸", iso2: "MS" },
  { name: "Morocco", code: "+212", short: "MAR", flag: "🇲🇦", iso2: "MA" },
  { name: "Mozambique", code: "+258", short: "MOZ", flag: "🇲🇿", iso2: "MZ" },
  { name: "Myanmar", code: "+95", short: "MMR", flag: "🇲🇲", iso2: "MM" },
  { name: "Namibia", code: "+264", short: "NAM", flag: "🇳🇦", iso2: "NA" },
  { name: "Nauru", code: "+674", short: "NRU", flag: "🇳🇷", iso2: "NR" },
  { name: "Nepal", code: "+977", short: "NPL", flag: "🇳🇵", iso2: "NP" },
  { name: "Netherlands", code: "+31", short: "NLD", flag: "🇳🇱", iso2: "NL" },
  { name: "New Caledonia", code: "+687", short: "NCL", flag: "🇳🇨", iso2: "NC" },
  { name: "Nicaragua", code: "+505", short: "NIC", flag: "🇳🇮", iso2: "NI" },
  { name: "Niger", code: "+227", short: "NER", flag: "🇳🇪", iso2: "NE" },
  { name: "Nigeria", code: "+234", short: "NGA", flag: "🇳🇬", iso2: "NG" },
  { name: "North Korea", code: "+850", short: "PRK", flag: "🇰🇵", iso2: "KP" },
  { name: "Norway", code: "+47", short: "NOR", flag: "🇳🇴", iso2: "NO" },
  { name: "Oman", code: "+968", short: "OMN", flag: "🇴🇲", iso2: "OM" },
  { name: "Pakistan", code: "+92", short: "PAK", flag: "🇵🇰", iso2: "PK" },
  { name: "Palau", code: "+680", short: "PLW", flag: "🇵🇼", iso2: "PW" },
  { name: "Palestine", code: "+970", short: "PSE", flag: "🇵🇸", iso2: "PS" },
  { name: "Panama", code: "+507", short: "PAN", flag: "🇵🇦", iso2: "PA" },
  { name: "Papua New Guinea", code: "+675", short: "PNG", flag: "🇵🇬", iso2: "PG" },
  { name: "Paraguay", code: "+595", short: "PRY", flag: "🇵🇾", iso2: "PY" },
  { name: "Peru", code: "+51", short: "PER", flag: "🇵🇪", iso2: "PE" },
  { name: "Philippines", code: "+63", short: "PHL", flag: "🇵🇭", iso2: "PH" },
  { name: "Poland", code: "+48", short: "POL", flag: "🇵🇱", iso2: "PL" },
  { name: "Portugal", code: "+351", short: "PRT", flag: "🇵🇹", iso2: "PT" },
  { name: "Puerto Rico", code: "+1-787", short: "PRI", flag: "🇵🇷", iso2: "PR" },
  { name: "Qatar", code: "+974", short: "QAT", flag: "🇶🇦", iso2: "QA" },
  { name: "Reunion", code: "+262", short: "REU", flag: "🇷🇪", iso2: "RE" },
  { name: "Romania", code: "+40", short: "ROU", flag: "🇷🇴", iso2: "RO" },
  { name: "Russia", code: "+7", short: "RUS", flag: "🇷🇺", iso2: "RU" },
  { name: "Rwanda", code: "+250", short: "RWA", flag: "🇷🇼", iso2: "RW" },
  { name: "Samoa", code: "+685", short: "WSM", flag: "🇼🇸", iso2: "WS" },
  { name: "San Marino", code: "+378", short: "SMR", flag: "🇸🇲", iso2: "SM" },
  { name: "Saudi Arabia", code: "+966", short: "SAU", flag: "🇸🇦", iso2: "SA" },
  { name: "Senegal", code: "+221", short: "SEN", flag: "🇸🇳", iso2: "SN" },
  { name: "Serbia", code: "+381", short: "SRB", flag: "🇷🇸", iso2: "RS" },
  { name: "Seychelles", code: "+248", short: "SYC", flag: "🇸🇨", iso2: "SC" },
  { name: "Sierra Leone", code: "+232", short: "SLE", flag: "🇸🇱", iso2: "SL" },
  { name: "Sint Maarten", code: "+1-721", short: "SXM", flag: "🇸🇽", iso2: "SX" },
  { name: "Slovakia", code: "+421", short: "SVK", flag: "🇸🇰", iso2: "SK" },
  { name: "Slovenia", code: "+386", short: "SVN", flag: "🇸🇮", iso2: "SI" },
  { name: "Solomon Islands", code: "+677", short: "SLB", flag: "🇸🇧", iso2: "SB" },
  { name: "Somalia", code: "+252", short: "SOM", flag: "🇸🇴", iso2: "SO" },
  { name: "South Africa", code: "+27", short: "ZAF", flag: "🇿🇦", iso2: "ZA" },
  { name: "South Korea", code: "+82", short: "KOR", flag: "🇰🇷", iso2: "KR" },
  { name: "South Sudan", code: "+211", short: "SSD", flag: "🇸🇸", iso2: "SS" },
  { name: "Spain", code: "+34", short: "ESP", flag: "🇪🇸", iso2: "ES" },
  { name: "Sri Lanka", code: "+94", short: "LKA", flag: "🇱🇰", iso2: "LK" },
  { name: "Sudan", code: "+249", short: "SDN", flag: "🇸🇩", iso2: "SD" },
  { name: "Suriname", code: "+597", short: "SUR", flag: "🇸🇷", iso2: "SR" },
  { name: "Swaziland", code: "+268", short: "SWZ", flag: "🇸🇿", iso2: "SZ" },
  { name: "Sweden", code: "+46", short: "SWE", flag: "🇸🇪", iso2: "SE" },
  { name: "Switzerland", code: "+41", short: "CHE", flag: "🇨🇭", iso2: "CH" },
  { name: "Syria", code: "+963", short: "SYR", flag: "🇸🇾", iso2: "SY" },
  { name: "Taiwan", code: "+886", short: "TWN", flag: "🇹🇼", iso2: "TW" },
  { name: "Tajikistan", code: "+992", short: "TJK", flag: "🇹🇯", iso2: "TJ" },
  { name: "Tanzania", code: "+255", short: "TZA", flag: "🇹🇿", iso2: "TZ" },
  { name: "Thailand", code: "+66", short: "THA", flag: "🇹🇭", iso2: "TH" },
  { name: "Timor-Leste", code: "+670", short: "TLS", flag: "🇹🇱", iso2: "TL" },
  { name: "Togo", code: "+228", short: "TGO", flag: "🇹🇬", iso2: "TG" },
  { name: "Tonga", code: "+676", short: "TON", flag: "🇹🇴", iso2: "TO" },
  { name: "Trinidad and Tobago", code: "+1-868", short: "TTO", flag: "🇹🇹", iso2: "TT" },
  { name: "Tunisia", code: "+216", short: "TUN", flag: "🇹🇳", iso2: "TN" },
  { name: "Turkey", code: "+90", short: "TUR", flag: "🇹🇷", iso2: "TR" },
  { name: "Turkmenistan", code: "+993", short: "TKM", flag: "🇹🇲", iso2: "TM" },
  { name: "Tuvalu", code: "+688", short: "TUV", flag: "🇹🇻", iso2: "TV" },
  { name: "Uganda", code: "+256", short: "UGA", flag: "🇺🇬", iso2: "UG" },
  { name: "Ukraine", code: "+380", short: "UKR", flag: "🇺🇦", iso2: "UA" },
  { name: "Uruguay", code: "+598", short: "URY", flag: "🇺🇾", iso2: "UY" },
  { name: "Uzbekistan", code: "+998", short: "UZB", flag: "🇺🇿", iso2: "UZ" },
  { name: "Vanuatu", code: "+678", short: "VUT", flag: "🇻🇺", iso2: "VU" },
  { name: "Vatican City", code: "+379", short: "VAT", flag: "🇻🇦", iso2: "VA" },
  { name: "Venezuela", code: "+58", short: "VEN", flag: "🇻🇪", iso2: "VE" },
  { name: "Vietnam", code: "+84", short: "VNM", flag: "🇻🇳", iso2: "VN" },
  { name: "Yemen", code: "+967", short: "YEM", flag: "🇾🇪", iso2: "YE" },
  { name: "Zambia", code: "+260", short: "ZMB", flag: "🇿🇲", iso2: "ZM" },
  { name: "Zimbabwe", code: "+263", short: "ZWE", flag: "🇿🇼", iso2: "ZW" },
];

/** Helper to find a country by dial code or default to Australia */
export function getCountryByCode(code: string): CountryData {
  return countryList.find((c) => c.code === code) || countryList[0];
}
